---
title: "Gabe's Vis"
author: "Gabe Runte"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(sf)
library(leaflet)
library(raster)
library(ggmap)
library(simplevis)
library(basemapR)

```

```{r}
master = read.csv(here("data", "Datasheets_and_Templates - SoilCoreMetadata.csv")) %>% 
  clean_names() %>% 
  dplyr::select(1:16)
cores_long = read_sf(here("data", "kmztoshp","Sedgwick_oaks_20220329-point.shp"))
cores_long$Name[cores_long$Name=="L23??"] = "L2331"
cores_long$Name[cores_long$Name=="B2373"] = "B2372"

cores = cores_long %>% 
  clean_names() %>% 
  mutate(number = substr(name, 2, 5)) %>% 
  mutate(number = as.numeric(number)) %>% 
  filter(number %in% master$tree_id) %>% 
  rename(tree_id = number)

missing_data = master %>% 
  filter(tree_id %in% cores$tree_id == FALSE)

samples = master %>% 
  filter(tree_id %in% missing_data$tree_id == FALSE)



total = samples %>% 
  right_join(cores) %>% 
  mutate(hole = rep(NaN, length(samples[1])))

for(i in 1:length(total$hole)) {
  total$hole[i] = total$geometry[i] + c(0.75/111000*sin(450 - total$heading[i]),0.75/111000*cos(450 - total$heading[i]))
  
}
total = total %>% 
  dplyr::select(!geometry) %>% 
  rename(geometry = hole)

total_sf = st_as_sf(total, crs = st_crs("WGS84"))

coordinates = tibble(as.data.frame(st_coordinates(total_sf))) %>% 
  rename(lat = X) %>% 
  rename(lng = Y)

total = as.data.frame(total) %>%
  tibble() %>% 
  bind_cols(coordinates)







```


```{r}

leaflet(data= test) %>% 
  addCircleMarkers(radius= 3, color = "pink",
    stroke = FALSE, fillOpacity = 0.75) %>% 
  addProviderTiles("Esri.WorldImagery")

gg_sf_col(test,
          col_var = uphill_downhill)

leaf_sf_col(test, 
               col_method = "quantile",
               col_cuts = seq(0, 1, 0.25))

test = st_as_sf(total, crs = st_crs("WGS84"))

leaf_sf_col(test, 
           basemap = map,
        col_var = unhill_downhill
        )

gg_sf_col(test,
          col_var = uphill_downhill) +
  leaf_basemap(bounds = c(-120.045,34.68940, -120.049,34.69190))


map = leaf_basemap(bounds = c(-120.045,34.68940, -120.049,34.69190)) 

ggplot(data = total %>% 
         filter(soil_pct_moist < 40), aes(x=lat, y=lng)) +
  geom_point(aes(color = soil_pct_moist, shape = tree_species))+
  scale_color_gradient2(midpoint = median(total$soil_pct_moist), low = "red", mid = "white",
                            high = "blue", space = "Lab" ) +
  theme_dark()

ggplot() +
  base_map(st_bbox(test), basemap = 'USGS-Topo', increase_zoom = 0,nolabels=TRUE) +
  geom_point(data = total%>% 
         filter(soil_pct_moist < 40), aes(x=lat, y=lng,color = soil_pct_moist,size = 3) )+
  scale_color_gradient2(midpoint = median(total$soil_pct_moist), low = "red", mid = "gray",
                            high = "blue", space = "Lab" )

```

```{r}
soil_nutes = read_csv(here("data", "soil_nutrients.csv")) %>% 
  clean_names()%>% 
  dplyr::select(c(1, 4:28))

soil_cn = read_csv(here("data", "soil_cn.csv")) %>% 
  clean_names() %>% 
  dplyr::select(c(1, 4:6))

soil_n = soil_cn %>% 
 left_join(soil_nutes) %>% 
  mutate(sample_location = paste(substr(sample_location, 1,5), substr(sample_location, 7,8), sep = "")) %>% 
  rename(sos_core_id = sample_location)


all = test %>% 
  left_join(soil_n) %>% 
  print()
```

```{r, eval = FALSE}
for_maggie = all %>% 
  dplyr::relocate(name, .before = env_weight) %>% 
  dplyr::select(9:49) %>% 
  write_csv(here("data", "sedgwick_nutrients.csv"))
```


```{r}
ggplot(all, aes(carbon_percent, nitrogen_percent, color = tree_species)) +
  geom_point()#+
  geom_smooth(method='lm') 
  
  ggplot(all, aes(tree_species, nitrogen_percent, color = tree_species)) +
  geom_boxplot()
  ggplot(all, aes(tree_species, total_exchange_capacity_meq_100_g, color = tree_species)) +
  geom_boxplot()
  ggplot(all, aes(tree_species, nitrogen_percent, color = tree_species)) +
  geom_boxplot()
  
  ggplot(all, aes(soil_pct_moist, total_exchange_capacity_meq_100_g, color = tree_species)) +
  geom_point()#+
  geom_smooth(method='lm') 


ggplot() +
  base_map(st_bbox(all), basemap = 'USGS-Topo', increase_zoom = 0,nolabels=TRUE) +
  geom_point(data = all, aes(x=lat, y=lng,color = c_n_ratio,size = 3) )+
  scale_color_gradient2(midpoint = median(all$c_n_ratio), low = "red", mid = "gray",
                            high = "blue", space = "Lab" )
```

```{r}
composite.master = read_csv(here("data", "sos composite locations - Sheet1.csv"))%>% # Here I am reading in the locations file
  clean_names() %>% 
  summarise()
sample = read_csv(here("data", "sos_tippulling_sequencing - sample_locations.csv"))%>%
  clean_names()

#left join, rename column and row in composite loc to new column and row. make old locations = to column and row in sample

composite = composite.master %>% 
  rename(new_column = column, new_row = row, new_plate_number = plate_number) %>% #changing the name of these columns to new_X instead of their old names in composite.master
  filter(!is.na(old_row)) %>%  
  mutate(old_column = as.numeric(old_column)) %>% 
  mutate(old_plate = as.numeric(old_plate))

master.joined = left_join(composite, sample, c("old_plate" = "plate_number", "old_column" = "column", "old_row" = "row"))

count.tips = master.joined %>% 
  rename(sos_core_id = sample) %>% 
  group_by(sos_core_id) %>% 
  summarise(tips_pulled = n())

all.tips = all %>% 
  left_join(count.tips)


ggplot(all.tips, aes(soil_pct_moist, tips_pulled, color = tree_species)) +
  geom_point()#+
  geom_smooth(method='lm') 

```
```























