---
title: "fungal root tips"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(RColorBrewer)
library(dbplyr)
```


```{r}
composite.master = read_csv(here("data", "sos_tippulling_sequencing - composite_locations.csv"))%>%
  clean_names()
```

```{r}
sample = read_csv(here("data", "sos_tippulling_sequencing - sample_locations.csv"))%>%
  clean_names()
```

```{r}
#left join, rename column and row in composite loc to new column and row. make old locations = to column and row in sample

composite = composite.master %>% 
  rename(new_column = column, new_row = row, new_plate_number = plate_number) %>% 
  filter(!is.na(old_row)) %>%  
  mutate(old_column = as.numeric(old_column)) %>% 
  mutate(old_plate = as.numeric(old_plate))
```

```{r}
master.joined = left_join(composite, sample, c("old_plate" = "plate_number", "old_column" = "column", "old_row" = "row"))
```

```{r}
not.amplified = master.joined %>% 
  filter(amplified_y_n == "N")
```

```{r}
plate_seq = rep(1:100, each = 96)
column_seq = rep(rep(1:12, each = 8),100)
row_seq = rep(rep(letters[1:8], 12), 100)

to.sequence = master.joined %>%
  filter(amplified_y_n == "Y")%>%
  mutate(sanger_plate = plate_seq[1:nrow(to.sequence)])%>%
   mutate(sanger_column = column_seq[1:nrow(to.sequence)]) %>% 
   mutate(sanger_row = row_seq[1:nrow(to.sequence)]) %>%
  relocate(sample, 1) 


printout.sanger = to.sequence  %>% 
  select(sample, new_plate_number, new_column, new_row, sanger_plate, sanger_column, sanger_row) %>% 
  write_csv(here("data", "sanger_plates_05022022.csv"))
```

